export const ACCESS_TOKEN = "access"
export const REFRESH_TOKEN = "refresh"
export const REGISTER_API_PATH = "api/v1/users/register/"
export const LOGIN_API_PATH = "api/v1/users/login/"
export const UPLOAD_API_PATH = "https://api.ringtonesglitch.com/api/v1/ringtones/upload/"
export const RINGTONE_COPY_PATH = "https://api.ringtonesglitch.com/ringtones/"